### PR TITLE
Add slots for next, previous & close buttons

### LINKED ISSUE #13: Slots for previous, next and close buttons
I would like to use my own custom SVG elements for the control buttons inside the lightbox, instead of the icons that are provided from within this package. I have a PR ready, but it seems I cannot push to any new branch.

### PR DESCRIPTION
**Pull request by keesvanlierop**
Fixes #13 by wrapping all lightbox control buttons with `<slot />`s.

### CODE REVIEW

**Comment by keesvanlierop** [comment]
@DCzajkowski Would you mind to give some feedback on this PR?

**Comment by DCzajkowski** [comment]
Sure! I'll look at it today or tomorrow. I've completly forgotten, sorry.

**Comment by keesvanlierop** [comment]
Pretty please? :)

**Comment by DCzajkowski** [comment]
I am sorry, but I haven't had any time whatsoever this week. Don't worry, I have this on my todo list. I'll get back to you soon. I'll try today, but I can't promise anything. Sorry.

**Comment by DCzajkowski** [comment]
I am terribly sorry it took so long. I have published [a new version](https://github.com/DCzajkowski/vue-pure-lightbox/releases/tag/2.1.9). New slots are documented here: https://github.com/DCzajkowski/vue-pure-lightbox/tree/2.1.9#available-slots.

**Pull request merged**
